// Writes facemesh.js: MediaPipe's canonical face mesh, read from the face model the
// site already ships (vendor/face_landmarker.task, a zip holding
// geometry_pipeline_metadata_landmarks.binarypb).
//
//   node tools/facemesh.cjs
//
// Makeup masks are painted once in this face's own space, a front-on view of the
// canonical face, and each frame the mesh carries them onto the live face. So the
// module holds, per landmark, where it sits in that front-on view, and the mesh's
// triangles without the ones spanning the eye and mouth openings: colour must never
// be stretched across an open mouth or an open eye.
const fs=require('fs'),path=require('path'),zlib=require('zlib');
const root=path.resolve(__dirname,'..');

function unzip(file,name){
  const b=fs.readFileSync(file);
  const eocd=b.lastIndexOf(Buffer.from([0x50,0x4b,0x05,0x06]));
  let p=b.readUInt32LE(eocd+16);
  for(let n=b.readUInt16LE(eocd+10);n--;){
    const method=b.readUInt16LE(p+10),size=b.readUInt32LE(p+20),nameLen=b.readUInt16LE(p+28);
    const extra=b.readUInt16LE(p+30),comment=b.readUInt16LE(p+32),local=b.readUInt32LE(p+42);
    const entry=b.toString('utf8',p+46,p+46+nameLen);
    if(entry===name){
      const start=local+30+b.readUInt16LE(local+26)+b.readUInt16LE(local+28);
      const data=b.subarray(start,start+size);
      return method===0?data:zlib.inflateRawSync(data);
    }
    p+=46+nameLen+extra+comment;
  }
  throw new Error(`${name} is not in ${file}`);
}

// Just enough protobuf: GeometryPipelineMetadata.canonical_mesh (1) is a Mesh3d whose
// vertex_buffer (3) holds x,y,z,u,v per vertex and index_buffer (4) the triangles.
function* fields(b){
  let o=0;
  const varint=()=>{let r=0,s=0,c;do{c=b[o++];r+=(c&0x7f)*2**s;s+=7;}while(c&0x80);return r;};
  while(o<b.length){
    const key=varint(),f=Math.floor(key/8),t=key&7;let v;
    if(t===0)v=varint();
    else if(t===2){const n=varint();v=b.subarray(o,o+n);o+=n;}
    else if(t===5){v=b.readFloatLE(o);o+=4;}
    else if(t===1){v=b.readDoubleLE(o);o+=8;}
    else throw new Error('unexpected wire type '+t);
    yield [f,t,v];
  }
}
const meta=unzip(path.join(root,'vendor/face_landmarker.task'),'geometry_pipeline_metadata_landmarks.binarypb');
const mesh=[...fields(meta)].find(([f])=>f===1)[2];
const verts=[],tris=[];
for(const [f,t,v] of fields(mesh)){
  if(f===3){if(t===5)verts.push(v);else for(let i=0;i<v.length;i+=4)verts.push(v.readFloatLE(i));}
  if(f===4){
    if(t===0)tris.push(v);
    else for(let o=0;o<v.length;){let r=0,s=0,c;do{c=v[o++];r+=(c&0x7f)*2**s;s+=7;}while(c&0x80);tris.push(r);}
  }
}
const N=verts.length/5;
if(N!==468||tris.length%3)throw new Error(`unexpected mesh: ${N} vertices, ${tris.length} indices`);

// The front-on view: x across, y down, one scale for both, a small margin all round.
const X=i=>verts[i*5],Y=i=>-verts[i*5+1];
let x0=Infinity,x1=-Infinity,y0=Infinity,y1=-Infinity;
for(let i=0;i<N;i++){x0=Math.min(x0,X(i));x1=Math.max(x1,X(i));y0=Math.min(y0,Y(i));y1=Math.max(y1,Y(i));}
const margin=.03*(x1-x0),w=x1-x0+2*margin,h=y1-y0+2*margin;
const canon=[];
for(let i=0;i<N;i++)canon.push(+((X(i)-x0+margin)/w).toFixed(5),+((Y(i)-y0+margin)/h).toFixed(5));

// The openings: triangles whose corners all lie on the inner lip line, or all on one
// eye's lid line.
const rings=[
  [78,191,80,81,82,13,312,311,310,415,308,324,318,402,317,14,87,178,88,95],
  [33,246,161,160,159,158,157,173,133,155,154,153,145,144,163,7],
  [263,466,388,387,386,385,384,398,362,382,381,380,374,373,390,249]
].map(r=>new Set(r));
const kept=[];let dropped=0;
for(let t=0;t<tris.length;t+=3){
  const tri=tris.slice(t,t+3);
  if(rings.some(r=>tri.every(i=>r.has(i)))){dropped++;continue;}
  kept.push(...tri);
}

const out=`// MediaPipe's canonical face mesh, from the face model in vendor/ (Apache-2.0, see
// THIRD-PARTY.md). Generated by tools/facemesh.cjs; do not edit.
//
// CANON: per landmark, x and y in a front-on view of the canonical face, as fractions
// of a frame CANON_ASPECT times as tall as it is wide. Masks are painted in this frame.
// TRIANGLES: the mesh, less the ${dropped} triangles that span the eye and mouth openings.
export const CANON_ASPECT=${+(h/w).toFixed(5)};
export const CANON=new Float32Array(${JSON.stringify(canon)});
export const TRIANGLES=new Uint16Array(${JSON.stringify(kept)});
`;
fs.writeFileSync(path.join(root,'facemesh.js'),out);
console.log(`facemesh.js: ${N} points, ${kept.length/3} triangles (${dropped} dropped), aspect ${(h/w).toFixed(4)}`);
